#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
    export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down


#boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
    picom --config "$SCRIPTPATH"/picom.conf &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
    compton &> /dev/null &
fi

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v feh)" ]; then
    feh --bg-scale $SCRIPTPATH/wallpapers/y1.jpg
fi

# ## Files and cmd
EWW="/usr/bin/eww"

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
    ${EWW} daemon &
    sleep 1
fi

## Open widgets
run_eww() {
    # ${EWW} open-many \
        #     bar
    ${EWW} open bar
}

## Launch or close widgets accordingly
run_eww
